# Generated by Django 4.2.9 on 2025-05-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_answer_unique_question_and_choice_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_answer_question', 'Can answer question')]},
        ),
    ]
